project:
  type: website

website:
  title: "Introduction to Python (part 1)"
  page-navigation: true

  sidebar:
    title: "Introduction to Python (part 1)"
    logo: "assets/logo.png"
    align: center
    logo-alt: "University of Bristol"
    style: "docked"
    border: true
    contents:
      - "index.qmd"

      # - "pages/001-programming.qmd"

      - "pages/010-workspace-setup.qmd"

      - "pages/020-hello-python.qmd"

      - section: "pages/030-variables.qmd"
        contents:
          - "pages/031-basic-data-types.qmd"
          - "pages/032-operators.qmd"
          - "pages/033-lists.qmd"
          - "pages/034-dictionaries.qmd"

      - section: "pages/050-control-structures.qmd"
        contents:
          - "pages/051-conditionals.qmd"
          - "pages/052-for.qmd"
          - "pages/053-while.qmd"
          - "pages/054-functions.qmd"

      - "pages/070-practical.qmd"

      - "pages/980-summary.qmd"

      - "pages/990-contributors.qmd"

  page-footer:
    left: "Course delivered by the [Jean Golding Institute](https://www.bristol.ac.uk/golding/)<br>© [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"

  repo-url: https://github.com/bristol-training/intro-python-1
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, style.scss]
    toc: true

execute:
  freeze: auto
